# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 941)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_General = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_General.sizePolicy().hasHeightForWidth())
        self.groupBox_General.setSizePolicy(sizePolicy)
        self.groupBox_General.setObjectName("groupBox_General")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_General)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Volume = QtWidgets.QLabel(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Volume.sizePolicy().hasHeightForWidth())
        self.label_Volume.setSizePolicy(sizePolicy)
        self.label_Volume.setObjectName("label_Volume")
        self.gridLayout.addWidget(self.label_Volume, 2, 1, 1, 1)
        self.lineEdit_Thickness = QtWidgets.QLineEdit(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Thickness.sizePolicy().hasHeightForWidth())
        self.lineEdit_Thickness.setSizePolicy(sizePolicy)
        self.lineEdit_Thickness.setObjectName("lineEdit_Thickness")
        self.gridLayout.addWidget(self.lineEdit_Thickness, 1, 3, 1, 1)
        self.lineEdit_Volume = QtWidgets.QLineEdit(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Volume.sizePolicy().hasHeightForWidth())
        self.lineEdit_Volume.setSizePolicy(sizePolicy)
        self.lineEdit_Volume.setObjectName("lineEdit_Volume")
        self.gridLayout.addWidget(self.lineEdit_Volume, 2, 3, 1, 1)
        self.label_Thickness = QtWidgets.QLabel(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Thickness.sizePolicy().hasHeightForWidth())
        self.label_Thickness.setSizePolicy(sizePolicy)
        self.label_Thickness.setObjectName("label_Thickness")
        self.gridLayout.addWidget(self.label_Thickness, 1, 1, 1, 1)
        self.lineEdit_Glass = QtWidgets.QLineEdit(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Glass.sizePolicy().hasHeightForWidth())
        self.lineEdit_Glass.setSizePolicy(sizePolicy)
        self.lineEdit_Glass.setObjectName("lineEdit_Glass")
        self.gridLayout.addWidget(self.lineEdit_Glass, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.textEdit_Description = QtWidgets.QTextEdit(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Description.sizePolicy().hasHeightForWidth())
        self.textEdit_Description.setSizePolicy(sizePolicy)
        self.textEdit_Description.setObjectName("textEdit_Description")
        self.gridLayout.addWidget(self.textEdit_Description, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_General, 6, 2, 2, 1)
        self.groupBox_R1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_R1.sizePolicy().hasHeightForWidth())
        self.groupBox_R1.setSizePolicy(sizePolicy)
        self.groupBox_R1.setObjectName("groupBox_R1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_R1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_R1_Coefs = QtWidgets.QTableWidget(self.groupBox_R1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_R1_Coefs.sizePolicy().hasHeightForWidth())
        self.tableWidget_R1_Coefs.setSizePolicy(sizePolicy)
        self.tableWidget_R1_Coefs.setMinimumSize(QtCore.QSize(256, 192))
        self.tableWidget_R1_Coefs.setObjectName("tableWidget_R1_Coefs")
        self.tableWidget_R1_Coefs.setColumnCount(0)
        self.tableWidget_R1_Coefs.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_R1_Coefs, 5, 0, 1, 3)
        self.comboBox_R1_Type = QtWidgets.QComboBox(self.groupBox_R1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_R1_Type.sizePolicy().hasHeightForWidth())
        self.comboBox_R1_Type.setSizePolicy(sizePolicy)
        self.comboBox_R1_Type.setObjectName("comboBox_R1_Type")
        self.comboBox_R1_Type.addItem("")
        self.comboBox_R1_Type.addItem("")
        self.comboBox_R1_Type.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_R1_Type, 3, 0, 1, 3)
        self.groupBox_R1_Diameter = QtWidgets.QGroupBox(self.groupBox_R1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_R1_Diameter.sizePolicy().hasHeightForWidth())
        self.groupBox_R1_Diameter.setSizePolicy(sizePolicy)
        self.groupBox_R1_Diameter.setObjectName("groupBox_R1_Diameter")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_R1_Diameter)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Diameter = QtWidgets.QLabel(self.groupBox_R1_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Diameter.sizePolicy().hasHeightForWidth())
        self.label_Diameter.setSizePolicy(sizePolicy)
        self.label_Diameter.setObjectName("label_Diameter")
        self.gridLayout_5.addWidget(self.label_Diameter, 0, 0, 1, 1)
        self.lineEdit_R1_Diameter_Outer = QtWidgets.QLineEdit(self.groupBox_R1_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_R1_Diameter_Outer.sizePolicy().hasHeightForWidth())
        self.lineEdit_R1_Diameter_Outer.setSizePolicy(sizePolicy)
        self.lineEdit_R1_Diameter_Outer.setObjectName("lineEdit_R1_Diameter_Outer")
        self.gridLayout_5.addWidget(self.lineEdit_R1_Diameter_Outer, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_R1_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_R1_Diameter_Inner = QtWidgets.QLineEdit(self.groupBox_R1_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_R1_Diameter_Inner.sizePolicy().hasHeightForWidth())
        self.lineEdit_R1_Diameter_Inner.setSizePolicy(sizePolicy)
        self.lineEdit_R1_Diameter_Inner.setObjectName("lineEdit_R1_Diameter_Inner")
        self.gridLayout_5.addWidget(self.lineEdit_R1_Diameter_Inner, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_R1_Diameter, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox_R1, 6, 1, 2, 1)
        self.groupBox_R2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_R2.sizePolicy().hasHeightForWidth())
        self.groupBox_R2.setSizePolicy(sizePolicy)
        self.groupBox_R2.setObjectName("groupBox_R2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_R2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_R2_Coefs = QtWidgets.QTableWidget(self.groupBox_R2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_R2_Coefs.sizePolicy().hasHeightForWidth())
        self.tableWidget_R2_Coefs.setSizePolicy(sizePolicy)
        self.tableWidget_R2_Coefs.setObjectName("tableWidget_R2_Coefs")
        self.tableWidget_R2_Coefs.setColumnCount(0)
        self.tableWidget_R2_Coefs.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_R2_Coefs, 4, 0, 1, 2)
        self.comboBox_R2_Type = QtWidgets.QComboBox(self.groupBox_R2)
        self.comboBox_R2_Type.setObjectName("comboBox_R2_Type")
        self.comboBox_R2_Type.addItem("")
        self.comboBox_R2_Type.addItem("")
        self.comboBox_R2_Type.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_R2_Type, 3, 0, 1, 2)
        self.groupBox_R2_Diameter = QtWidgets.QGroupBox(self.groupBox_R2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_R2_Diameter.sizePolicy().hasHeightForWidth())
        self.groupBox_R2_Diameter.setSizePolicy(sizePolicy)
        self.groupBox_R2_Diameter.setObjectName("groupBox_R2_Diameter")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_R2_Diameter)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_R2_Diameter_Outer = QtWidgets.QLineEdit(self.groupBox_R2_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_R2_Diameter_Outer.sizePolicy().hasHeightForWidth())
        self.lineEdit_R2_Diameter_Outer.setSizePolicy(sizePolicy)
        self.lineEdit_R2_Diameter_Outer.setObjectName("lineEdit_R2_Diameter_Outer")
        self.gridLayout_6.addWidget(self.lineEdit_R2_Diameter_Outer, 0, 1, 1, 1)
        self.lineEdit_R2_Diameter_Inner = QtWidgets.QLineEdit(self.groupBox_R2_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_R2_Diameter_Inner.sizePolicy().hasHeightForWidth())
        self.lineEdit_R2_Diameter_Inner.setSizePolicy(sizePolicy)
        self.lineEdit_R2_Diameter_Inner.setObjectName("lineEdit_R2_Diameter_Inner")
        self.gridLayout_6.addWidget(self.lineEdit_R2_Diameter_Inner, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_R2_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_R2_Diameter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_R2_Diameter, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_R2, 6, 3, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 3, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_AddLens = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddLens.sizePolicy().hasHeightForWidth())
        self.pushButton_AddLens.setSizePolicy(sizePolicy)
        self.pushButton_AddLens.setObjectName("pushButton_AddLens")
        self.verticalLayout.addWidget(self.pushButton_AddLens)
        self.pushButton_DeleteLens = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeleteLens.sizePolicy().hasHeightForWidth())
        self.pushButton_DeleteLens.setSizePolicy(sizePolicy)
        self.pushButton_DeleteLens.setObjectName("pushButton_DeleteLens")
        self.verticalLayout.addWidget(self.pushButton_DeleteLens)
        self.listWidget_Lens = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Lens.sizePolicy().hasHeightForWidth())
        self.listWidget_Lens.setSizePolicy(sizePolicy)
        self.listWidget_Lens.setObjectName("listWidget_Lens")
        self.verticalLayout.addWidget(self.listWidget_Lens)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Draw = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_Draw.sizePolicy().hasHeightForWidth())
        self.tab_Draw.setSizePolicy(sizePolicy)
        self.tab_Draw.setObjectName("tab_Draw")
        self.tabWidget.addTab(self.tab_Draw, "")
        self.tab_R1_Data = QtWidgets.QWidget()
        self.tab_R1_Data.setObjectName("tab_R1_Data")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_R1_Data)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_R1_Data = QtWidgets.QTableWidget(self.tab_R1_Data)
        self.tableWidget_R1_Data.setObjectName("tableWidget_R1_Data")
        self.tableWidget_R1_Data.setColumnCount(0)
        self.tableWidget_R1_Data.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_R1_Data)
        self.tabWidget.addTab(self.tab_R1_Data, "")
        self.tab_R2_Data = QtWidgets.QWidget()
        self.tab_R2_Data.setObjectName("tab_R2_Data")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_R2_Data)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_R2_Data = QtWidgets.QTableWidget(self.tab_R2_Data)
        self.tableWidget_R2_Data.setObjectName("tableWidget_R2_Data")
        self.tableWidget_R2_Data.setColumnCount(0)
        self.tableWidget_R2_Data.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget_R2_Data)
        self.tabWidget.addTab(self.tab_R2_Data, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_SaveAs = QtWidgets.QAction(MainWindow)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_SaveAs)
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_General.setTitle(_translate("MainWindow", "General"))
        self.label_Volume.setText(_translate("MainWindow", "Volume:"))
        self.label_Thickness.setText(_translate("MainWindow", "Thickness: "))
        self.label.setText(_translate("MainWindow", "Glass: "))
        self.label_5.setText(_translate("MainWindow", "note:"))
        self.groupBox_R1.setTitle(_translate("MainWindow", "Left Surface"))
        self.comboBox_R1_Type.setItemText(0, _translate("MainWindow", "Sphere"))
        self.comboBox_R1_Type.setItemText(1, _translate("MainWindow", "Even Asphere"))
        self.comboBox_R1_Type.setItemText(2, _translate("MainWindow", "Odd Asphere"))
        self.groupBox_R1_Diameter.setTitle(_translate("MainWindow", "Diameters"))
        self.label_Diameter.setText(_translate("MainWindow", "Outer:"))
        self.label_3.setText(_translate("MainWindow", "Inner:"))
        self.groupBox_R2.setTitle(_translate("MainWindow", "Right Surface"))
        self.comboBox_R2_Type.setItemText(0, _translate("MainWindow", "Sphere"))
        self.comboBox_R2_Type.setItemText(1, _translate("MainWindow", "Even Asphere"))
        self.comboBox_R2_Type.setItemText(2, _translate("MainWindow", "Odd Asphere"))
        self.groupBox_R2_Diameter.setTitle(_translate("MainWindow", "Diameters"))
        self.label_4.setText(_translate("MainWindow", "Inner:"))
        self.label_2.setText(_translate("MainWindow", "Outer:"))
        self.pushButton_AddLens.setText(_translate("MainWindow", "Add Lens"))
        self.pushButton_DeleteLens.setText(_translate("MainWindow", "Delete Lens"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Draw), _translate("MainWindow", "Draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_R1_Data), _translate("MainWindow", "Left"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_R2_Data), _translate("MainWindow", "Right"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_About.setText(_translate("MainWindow", "About"))
        self.action_New.setText(_translate("MainWindow", "New"))
        self.action_Open.setText(_translate("MainWindow", "Open"))
        self.action_Save.setText(_translate("MainWindow", "Save"))
        self.action_SaveAs.setText(_translate("MainWindow", "Save as"))

